### PR TITLE
Update plugins.json

### PR DESCRIPTION
**Pull request by paweldudek**
Added duplicate localizable strings plugin to list of danger plugins.

### CODE REVIEW

**Comment by orta** [comment]
Any chance you can rebase this? I've made some Danger changes which should mean that we get a preview of what this looks like on the site in this PR

**Comment by paweldudek** [comment]
Rebased!

**Comment by orta** [comment]
aww - it should have echo'd out 

Ah! No, it's going across forks. Silly me

**Comment by orta** [comment]
OK with #84 - can you try another rebase? sorry, infrastructure-y things

**Comment by orta** [comment]
poke

**Comment by paweldudek** [comment]
And done!

**Comment by orta** [comment]
Interesting, well, that would have crashed the website, I'll have to clone the repo and see what's up

**Comment by paweldudek** [comment]
@orta any updates on this? How can I help out?

**Comment by orta** [comment]
Ah yeah, wanna try give it a rebase?

**Comment by orta** [comment]
Awesome, I'll get this merged and ported over to GitLab - where this actually exists

**Comment by paweldudek** [comment]
Awesome, thanks! 🎉

**Pull request merged**
