### PR TITLE
[Plugins] the_coding_love | xcodebuild | junit_results | podliblint

### PR DESCRIPTION
**Pull request by valeriomazzeo**
## Plugins

* [danger-the_coding_love](https://github.com/valeriomazzeo/danger-the_coding_love)
* [danger-xcodebuild](https://github.com/valeriomazzeo/danger-xcodebuild)
* [danger-junit_results](https://github.com/valeriomazzeo/danger-junit_results)
* [danger-podliblint](https://github.com/valeriomazzeo/danger-podliblint)

### CODE REVIEW

**Comment by orta** [comment]
This might take a little bit, I need to integrate danger and to have her show the results of `bundle exec danger plugins readme` on your repo in here first

**Comment by valeriomazzeo** [comment]
There are two more to come :)

**Comment by orta** [comment]
I still need to do some work on the CI so we can talk about how well documentented these are, but I definitely don't want to have two junit plugins - I wrote one two weeks ago https://github.com/orta/danger-junit/

**Comment by valeriomazzeo** [comment]
The junit plugin I wrote it few months ago, then I just ported it to be a plugin.
I think the main difference is in the report, as yours report as a table mine reports as `failures`.

**Comment by orta** [comment]
Interesting, do you have any PRs with it showing still?

**Comment by valeriomazzeo** [comment]
I try and post a screenshot as soon as I can

**Comment by orta** [comment]
Alright, sorry for the delay, any chance you can rebase this? I've made some Danger changes which should mean that we get a preview of what this looks like on the site in this PR

**Comment by valeriomazzeo** [comment]
done

**Comment by orta** [comment]
Any chance you could give this another rebase? Sorry, think the Dangerfile should be correct now

**Comment by orta** [comment]
Awesome, looks good

**Comment by valeriomazzeo** [comment]
👍

**Pull request merged**
