### PR TITLE
Guides Preparation

### PR DESCRIPTION
**Pull request by orta**
Improves some of the vertical spacing
Adds links to the headers, so people can quickly refer to them

screen shot 2016-07-16 at 08 19 01

### CODE REVIEW

**Comment by orta** [comment]
Also, _finally_ includes nokogiri.

**Comment by orta** [comment]
As though any web project I do could ever not use it.

**Comment by KrauseFx** [comment]
nokogiri

**Comment by orta** [comment]
http://www.nokogiri.org/tutorials/installing_nokogiri.html

screen shot 2016-07-16 at 09 34 50

I found this interesting, perhaps it's less bad now.

**Comment by orta** [comment]
We did this for CocoaPods for something, to also skip the `installing native extensions` thing.

**Pull request merged**
