### PR TITLE
[Meta] Add notice to PRs about GitLab

### PR DESCRIPTION
**Pull request by k0nserv**
This adds a note about the move to GitLab when submitting PRs to this repo

### CODE REVIEW

**Comment by orta** [comment]
whoah

clever

**Comment by orta** [comment]
`danger.scm_provider`

**Comment by k0nserv** [comment]
I figured that might be it. I have written very few(0) Dangerfiles for someone who works on the project 😂

**Comment by orta** [comment]
👏

**Comment by k0nserv** [comment]
Maybe it should be an error instead?

**Comment by orta** [comment]
I'm nonchalant on it, your call, this makes it possible to still merge easily

**Comment by k0nserv** [comment]
Warning seems like a good compromise then

**Pull request merged**
