### PR TITLE
Adds the Commit Lint plugin

### PR DESCRIPTION
**Pull request by jonallured**
I think it's a good one! What was once 5 lines of Ruby in a Dangerfile is now over 450 lines of code in the form of a well-tested and documented gem.

Am I doing this right?? 😀  😀  😀 

Check it: https://github.com/jonallured/danger-commit_lint

### CODE REVIEW

**Comment by jonallured** [comment]
Hmmm, I'm green when I run `bundle exec danger plugins lint` on my machine - what am I missing??

**Comment by orta** [comment]
This bit is wrong in the Dangerfile: `    markdown "### Failed to parse #{plugin}" if $0 != 0` it should be `unless $0.success?` the `$0` does not represent the error code, but an object, so it always fails

**Comment by orta** [comment]
So this is almost perfect - ideally, I'd love to see your usage section move into the comments above the class, so that you know what the checks are by just looking at the overview we see above ( which is what'll show on the site. ) 

Right now you don't know what it's going to check for without going to a different repo - which ideally can get fixed in the next release - other than that, this looks awesome!

**Comment by orta** [comment]
Great job 👍

**Comment by jonallured** [comment]
Yeah, I think it'll really help to see this on the site and then I can tweak it from there. ❤️  ❤️  ❤️

**Pull request merged**
