### PR TITLE
[WIP] Add danger-todoist to plugins

### PR DESCRIPTION
**Pull request by hanneskaeufler**
This adds a still wip plugin https://github.com/hanneskaeufler/danger-todoist to the list. Just pinging to see if this is a plugin you'd think is worth including.

### CODE REVIEW

**Comment by orta** [comment]
IMO, yeah, this would be worth it 👍 - get it passing `bundle exec plugins lint`

**Comment by orta** [comment]
@dbgrandi says this should have a closure API so that you can loop through all the TODOs and run against the code ( for example to see if it includes a JIRA ticket )

**Comment by hanneskaeufler** [comment]
It does/did already pass `danger plugins lint`. I think this fails as long as the plugin in not pushed to rubygems yet? Which I did by now. Will force push again...

**Comment by orta** [comment]
Ah, yeah, legit - the dangerfile should let us know. 

So while this PR has been opened - we've [moved to GitLab](https://gitlab.com/danger-systems/danger.systems/) - where this PR got copied, so if this looks good I'll [merge it there](https://gitlab.com/danger-systems/danger.systems/merge_requests/108), and close this one

**Comment by orta** [comment]
handled in gitlab 👍

**Pull request closed without merging**
