### PR TITLE
Adding danger-simplecov_json to plugins.json

### PR DESCRIPTION
**Pull request by marcelofabri**
My first open source plugin 😅

### CODE REVIEW

**Comment by marcelofabri** [comment]
"Failed to parse" doesn't look good 😬

**Comment by orta** [comment]
Alright, this looks good - the Dangerfile's wording must be wrong, but sure, this'll need a rebase, as you're there, can you turn it for one LOC to many? We're going to get a  lot of "can you rebases" otherwise 💃

**Comment by marcelofabri** [comment]
Rebased 💯

**Comment by orta** [comment]
Rock, site building is down AMT but should be able to get it back up this eve

**Pull request merged**
